### ISSUE TITLE
Ability to pass in IAM role ARN to assume

### ISSUE THREAD

**Issue by robertstettner** [appleboy/drone-packer#14]
It would be really nice when using AWS with this plugin to be able to pass in a IAM role to the plugin, so that it can be assumed for credentials before running the `packer build` command.

**Example:**
```yaml
- name: packer
    image: appleboy/drone-packer
    settings:
      assume_role: arn:aws:iam::123456789012:role/my-role-name
      actions:
        - validate
        - build
      template: aws.json
```
