### ISSUE TITLE
Run packer init before building

### ISSUE THREAD

**Issue by ebanDev** [appleboy/drone-packer#18]
![image](https://user-images.githubusercontent.com/57091497/140074882-8b152aac-7144-4912-98a8-e5d899db5e81.png)
In order to fix this issue we should run `packer init` to install plugins

**Comment by appleboy** [comment]
OK I will take it.

**Comment by appleboy** [comment]
```yaml
kind: pipeline
name: default

steps:
- name: packer
  image: appleboy/drone-packer
  settings:
    template: aws-ubuntu.pkr.hcl
    actions: init
```
