### ISSUE TITLE
packer init doesn't work

### ISSUE THREAD

**Issue by clumbo** [appleboy/drone-packer#24]
When running this plugin it doesn't run packer init properly, you have to pass a folder like so

`packer init .`

**Comment by appleboy** [comment]
```yaml
kind: pipeline
name: default

steps:
- name: packer
  image: appleboy/drone-packer
  settings:
    template: aws-ubuntu.pkr.hcl
    actions: init
```
